### ISSUE TITLE
removing bb-trackTitle then no pauze btn

### ISSUE THREAD

**Issue by fourroses666** [73rhodes/bbplayer#12]
Weird, but when removing tracktitle then pauze is not visible. (play keeps visible)
`<span class="bb-trackTitle"></span>`

thanks anyway :) did a display none

**Comment by darrenderidder** [comment]
Note: Throws errors in `updateDisplay` when requested DOM elements not present. Make them optional and check for presence before dereferencing.

**Comment by fourroses666** [comment]
:+1:

**Comment by 73rhodes** [comment]
Should fix this.
