### ISSUE TITLE
Shoutcast stream

### ISSUE THREAD

**Issue by ultrabr** [73rhodes/bbplayer#13]
Hi. I'm using the player for shoutcast streaming in autoplayer, works ok, but after 30 minutes of music playing, the player stop. I need to press play again. What can it be ? I'm using version six months ago, there have been changes? Thanks.

**Comment by 73rhodes** [comment]
Can you provide a URL or source code example for the issue?

**Comment by 73rhodes** [comment]
Closing due to lack of response / detail.
